version: '3'
services:
        backend:
                image: kohonski/csv-demo-backend
                container_name: backend
                build: ./backend
                environment:
                        - DOMAIN=localhost
                        - DJANGO_SETTINGS_MODULE=config.settings.local
                expose: 
                        - 8000
                volumes:
                        - static:/var/www/static

        frontend:
                image: kohonski/csv-demo-frontend
                container_name: frontend
                build: ./frontend
        nginx:
                image: kohonski/csv-demo-nginx
                container_name: nginx
                build: ./nginx
                environment:
                        - USE_LETSENCRYPT=F
                        - DOMAIN=localhost
                links:
                        - backend
                        - frontend
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - static:/static
                        - ./nginx/ssl:/certificates
volumes:
        static: 
