version: '3'
services:
        backend:
                image: csv-demo/backend
                container_name: backend
                build: ./backend
                environment:
                        - DOMAIN=localhost
                        - DJANGO_SETTINGS_MODULE=config.settings
                expose: 
                        - 8000
                volumes:
                        - static:/var/www/static

        frontend:
                image: csv-demo/frontend
                container_name: frontend
                build: ./frontend
        nginx:
                image: csv-demo/nginx
                container_name: nginx
                build: ./nginx
                environment:
                        - DOMAIN=localhost
                links:
                        - backend
                        - frontend
                ports:
                        - "80:80"
                volumes:
                        - static:/static
volumes:
        static: 
