version: '3'
services:
        backend:
                build: ./backend
                image: csv-demo-backend
                expose: 
                        - 8000
        frontend:
                build: ./frontend
                image: csv-demo-frontend

